runtime: python311
instance_class: F2
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  BUCKET_NAME: "bridgewater-state-university.appspot.com"
  GOOGLE_CLOUD_PROJECT: "bridgewater-state-university"