runtime: python312

handlers:
  - url: /.*
    script: auto  # Routes all URLs to your application

env_variables:
  CLOUD_SQL_USERNAME: steven
  CLOUD_SQL_PASSWORD: BSU123
  CLOUD_SQL_DATABASE_NAME: class
  CLOUD_SQL_CONNECTION_NAME: bridgewater-state-university:northamerica-northeast1:class-db
  SECRET_KEY: "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"
  CLIENT_SECRET_FILE: "client_secrets.json"
  GOOGLE_APPLICATION_CREDENTIALS: "bridgewater-state-university.json"